@startuml
:ciudadano:
:ciudadano2:

(Registrar entrada)
(Tomar huellas)


ciudadano--(Registrar entrada)
ciudadano2--(Tomar huellas)

(Tomar huellas) ..> (Registrar entrada) : extend

ciudadano2 --|> ciudadano

@enduml