@startuml
:usuario:
:Administrador:

(Iniciar sesion)
(Recuperar contra)
(Modificar contra)
(Cerrar sesion)
(Registrar usuario)
(Instalar programa)


usuario--(Iniciar sesion)
usuario--(Recuperar contra)
usuario--(Modificar contra)
usuario--(Cerrar sesion)

Administrador --|> usuario

Administrador -- (Registrar usuario)
Administrador - (Instalar programa)

@enduml